### ISSUE TITLE
python

### ISSUE THREAD

**Issue by RohiniVasudev** [RohiniVasudev/coding#2]
i dont understand map,lambda in python i........

**Comment by RohiniVasudev** [comment]
map() function returns a map object(which is an iterator) of the results after applying the given function to each item of a given iterable (list, tuple etc.)

Syntax :

map(fun, iter)

**Comment by Ro-1105** [comment]
map() function returns a map object(which is an iterator) of the results after applying the given function to each item of a given iterable (list, tuple etc.)

Syntax :

map(fun, iter)

**Comment by RohiniVasudev** [comment]
> i dont understand map,lambda in python i........

**Comment by RohiniVasudev** [comment]
thank you
